-- CreateTable
CREATE TABLE `TD_Order` (
    `Order_No` VARCHAR(191) NOT NULL,
    `Product_Grp_CD` VARCHAR(191) NULL,
    `Customer_CD` VARCHAR(191) NULL,
    `NAV_Name` VARCHAR(191) NULL,
    `Product_Name` VARCHAR(191) NULL,
    `NAV_Size` VARCHAR(191) NULL,
    `Product_Size` VARCHAR(191) NULL,
    `Tolerance` VARCHAR(191) NULL,
    `Customer_Draw` VARCHAR(191) NULL,
    `Company_Draw` VARCHAR(191) NULL,
    `Product_Draw` VARCHAR(191) NULL,
    `Quantity` INTEGER NULL,
    `Pd_Target_Qty` INTEGER NULL,
    `Pd_Complete_Qty` INTEGER NULL,
    `I_Complete_Qty` INTEGER NULL,
    `Shipment_Qty` INTEGER NULL,
    `Pd_Split_Qty` INTEGER NULL,
    `Pd_Calc_Qty` INTEGER NULL,
    `NG_Qty` INTEGER NULL,
    `Unit_CD` VARCHAR(191) NULL,
    `Sales_Grp_CD` VARCHAR(191) NULL,
    `Sales_Person_CD` VARCHAR(191) NULL,
    `Request1_CD` VARCHAR(191) NULL,
    `Request2_CD` VARCHAR(191) NULL,
    `Request3_CD` VARCHAR(191) NULL,
    `Material1` VARCHAR(191) NULL,
    `H_Treatment1` VARCHAR(191) NULL,
    `Material2` VARCHAR(191) NULL,
    `H_Treatment2` VARCHAR(191) NULL,
    `Material3` VARCHAR(191) NULL,
    `H_Treatment3` VARCHAR(191) NULL,
    `Material4` VARCHAR(191) NULL,
    `H_Treatment4` VARCHAR(191) NULL,
    `Material5` VARCHAR(191) NULL,
    `H_Treatment5` VARCHAR(191) NULL,
    `Coating_CD` VARCHAR(191) NULL,
    `Coating` VARCHAR(191) NULL,
    `Quote_No` VARCHAR(191) NULL,
    `Quote_CD` VARCHAR(191) NULL,
    `Od_No_of_Pd_Split` VARCHAR(191) NULL,
    `ItemO_CD` VARCHAR(191) NULL,
    `Item1_CD` VARCHAR(191) NULL,
    `Item2_CD` VARCHAR(191) NULL,
    `Item3_CD` VARCHAR(191) NULL,
    `Item4_CD` VARCHAR(191) NULL,
    `Custom_Material` VARCHAR(191) NULL,
    `Od_No_of_Custom` VARCHAR(191) NULL,
    `Supply_CD` VARCHAR(191) NULL,
    `Destination_CD` VARCHAR(191) NULL,
    `Contract_Docu_CD` VARCHAR(191) NULL,
    `Price_CD` VARCHAR(191) NULL,
    `Unit_Price` DOUBLE NULL,
    `Specific_CD` VARCHAR(191) NULL,
    `Od_Progress_CD` VARCHAR(191) NULL,
    `Delivery_CD` VARCHAR(191) NULL,
    `Schedule_CD` VARCHAR(191) NULL,
    `Target_CD` VARCHAR(191) NULL,
    `Product_Docu` VARCHAR(191) NULL,
    `Procure_Docu` VARCHAR(191) NULL,
    `Outside_Docu` VARCHAR(191) NULL,
    `Inspect_Docu` VARCHAR(191) NULL,
    `Send_Docu` VARCHAR(191) NULL,
    `Supple_Docu` VARCHAR(191) NULL,
    `Sl_Instructions` VARCHAR(191) NULL,
    `Pd_Instructions` VARCHAR(191) NULL,
    `Pd_Remark` VARCHAR(191) NULL,
    `I_Remark` VARCHAR(191) NULL,
    `Od_Ctl_Person_CD` VARCHAR(191) NULL,
    `Od_Reg_Person_CD` VARCHAR(191) NULL,
    `Od_Upd_Person_CD` VARCHAR(191) NULL,
    `Request_Delivery` DATETIME(3) NULL,
    `Product_Delivery` DATETIME(3) NULL,
    `Confirm_Delivery` DATETIME(3) NULL,
    `NAV_Delivery` DATETIME(3) NULL,
    `ASP_Delivery` DATETIME(3) NULL,
    `Order_Date` DATETIME(3) NULL,
    `Pd_Received_Date` DATETIME(3) NULL,
    `Pd_Complete_Date` DATETIME(3) NULL,
    `I_Completed_Date` DATETIME(3) NULL,
    `Shipment_Date` DATETIME(3) NULL,
    `Pd_Calc_Date` DATETIME(3) NULL,
    `Calc_Process_Date` DATETIME(3) NULL,
    `Rs_Confirm_Date` DATETIME(3) NULL,
    `Od_Reg_Date` DATETIME(3) NULL,
    `Od_Upd_Date` DATETIME(3) NULL,
    `Od_NAV_Upd_Date` DATETIME(3) NULL,
    `Carbide_Cost` DOUBLE NULL,
    `Steel_Cost` DOUBLE NULL,
    `Outsourcing_Cost` DOUBLE NULL,
    `H_Treatment_Cost` DOUBLE NULL,
    `Coating_Cost` DOUBLE NULL,
    `Electrode_Cost` DOUBLE NULL,
    `Electroplate_Cost` DOUBLE NULL,
    `Tooling_Cost` DOUBLE NULL,
    `Jig_Cost` DOUBLE NULL,
    `Fixtures_Cost` DOUBLE NULL,
    `Od_CAT1` BOOLEAN NULL,
    `Od_CAT2` BOOLEAN NULL,
    `Od_CAT3` BOOLEAN NULL,
    `Od_Pending` BOOLEAN NULL,
    `Temp_Shipment` BOOLEAN NULL,
    `Unreceived` BOOLEAN NULL,
    `Current_Order` BOOLEAN NULL,
    `Month_Plan` BOOLEAN NULL,
    `Week_Plan` BOOLEAN NULL,
    `Today_Plan` BOOLEAN NULL,
    `Must_Delivery` BOOLEAN NULL,
    `Into_I` BOOLEAN NULL,
    `Input_Confirm` BOOLEAN NULL,
    `Pd_Confirm` BOOLEAN NULL,
    `I_Confirm` BOOLEAN NULL,
    `Od_Confirm` BOOLEAN NULL,
    `I_Target` BOOLEAN NULL,
    `Urgent_Goods` BOOLEAN NULL,

    PRIMARY KEY (`Order_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Procure` (
    `Order_No` VARCHAR(191) NOT NULL,
    `Procure_No` VARCHAR(191) NULL,
    `OdPc_No` VARCHAR(191) NULL,
    `OdPcLn_No` VARCHAR(191) NOT NULL,
    `Vendor_CAT` VARCHAR(191) NULL,
    `Vendor_CD` VARCHAR(191) NULL,
    `Pc_Name` VARCHAR(191) NULL,
    `Pc_Material` VARCHAR(191) NULL,
    `Pc_Mate_Docu` VARCHAR(191) NULL,
    `Temp_Price` VARCHAR(191) NULL,
    `Unit_Price` DOUBLE NULL,
    `Yes_No_1` BOOLEAN NULL,
    `Yes_No_2` BOOLEAN NULL,
    `Short_Text_1` VARCHAR(191) NULL,
    `Number_1` VARCHAR(191) NULL,
    `Number_2` VARCHAR(191) NULL,
    `Pc_Qty` VARCHAR(191) NULL,
    `Pc_Unit_CD` VARCHAR(191) NULL,
    `Pc_Person_CD` VARCHAR(191) NULL,
    `Pc_Date` DATETIME(3) NULL,
    `Pc_Req_Delivery` DATETIME(3) NULL,
    `Pc_Req_Delivery_CD` VARCHAR(191) NULL,
    `Pc_Ans_Delivery` DATETIME(3) NULL,
    `Pc_Ans_Delivery_CD` VARCHAR(191) NULL,
    `Pc_Delivery_Judge` VARCHAR(191) NULL,
    `Pc_Progress_CD` VARCHAR(191) NULL,
    `Pc_Send_Date` DATETIME(3) NULL,
    `Pc_Arrival_Date` DATETIME(3) NULL,
    `Pc_Arrival_Qty` VARCHAR(191) NULL,
    `Pc_Cancel_Date` DATETIME(3) NULL,
    `Procure_Docu` VARCHAR(191) NULL,
    `Pc_Remark` VARCHAR(191) NULL,
    `Print` BOOLEAN NULL,
    `Pc_Reg_Date` DATETIME(3) NULL,
    `Pc_Upd_Date` DATETIME(3) NULL,
    `Pc_NAV_Reg_Date` DATETIME(3) NULL,
    `PC_NAV_Upd_Date` DATETIME(3) NULL,
    `Pc_Line_No` VARCHAR(191) NULL,

    PRIMARY KEY (`OdPcLn_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Plan` (
    `Order_No` VARCHAR(191) NOT NULL,
    `Parts_No` VARCHAR(191) NOT NULL,
    `OdPt_No` VARCHAR(191) NULL,
    `Parts_CD` VARCHAR(191) NULL,
    `Pt_Material` VARCHAR(191) NULL,
    `Pt_Qty` INTEGER NULL,
    `Pt_Unit_CD` VARCHAR(191) NULL,
    `Pt_Split` BOOLEAN NULL,
    `Pt_Spare_Qty` INTEGER NULL,
    `Pt_NG_Qty` INTEGER NULL,
    `Pt_l_Comp_Qty` INTEGER NULL,
    `Connect_Od_No` VARCHAR(191) NULL,
    `Connect_Pt_No` VARCHAR(191) NULL,
    `Connect_Pr_No` INTEGER NULL,
    `Pl_Quote_OdPt_No` VARCHAR(191) NULL,
    `PI_Quote_CD` VARCHAR(191) NULL,
    `PI_St_Rev_Day` INTEGER NULL,
    `Pl_Ed_Rev_Day` INTEGER NULL,
    `Pl_Progress_CD` INTEGER NULL,
    `PI_Schedule_CD` VARCHAR(191) NULL,
    `Pt_Instructions` VARCHAR(191) NULL,
    `Pt_Remark` VARCHAR(191) NULL,
    `Pt_Information` VARCHAR(191) NULL,
    `Pl_Reg_Person_CD` VARCHAR(191) NULL,
    `PI_Upd_Person_CD` VARCHAR(191) NULL,
    `Pt_Delivery` DATETIME(3) NULL,
    `Target_Delivery` DATETIME(3) NULL,
    `PI_Reg_Date` DATETIME(3) NULL,
    `Pt_Complete_Date` DATETIME(3) NULL,
    `Pt_I_Date` DATETIME(3) NULL,
    `Pt_Shipment_Date` DATETIME(3) NULL,
    `Pt_Calc_Date` DATETIME(3) NULL,
    `Pt_Confirm_Date` DATETIME(3) NULL,
    `PI_Upd_Date` DATETIME(3) NULL,
    `Pl_Month_Plan` BOOLEAN NULL,
    `PI_Wweek_Plan` BOOLEAN NULL,
    `PI_Today_Plan` BOOLEAN NULL,
    `Pt_CAT1` BOOLEAN NULL,
    `Pt_CAT2` BOOLEAN NULL,
    `Pt_CAT3` BOOLEAN NULL,
    `Money_Object` BOOLEAN NULL,
    `Outside` BOOLEAN NULL,
    `Pt_Pending` BOOLEAN NULL,
    `Info1` VARCHAR(191) NULL,
    `Info2` VARCHAR(191) NULL,
    `Info3` VARCHAR(191) NULL,
    `Info4` VARCHAR(191) NULL,
    `Info5` VARCHAR(191) NULL,
    `Info6` VARCHAR(191) NULL,
    `Info_Chk1` BOOLEAN NULL,
    `Info_Chk2` BOOLEAN NULL,
    `Info_Chk3` BOOLEAN NULL,
    `Info_Chk4` BOOLEAN NULL,
    `Info_Chk5` BOOLEAN NULL,
    `Info_Chk6` BOOLEAN NULL,
    `Max_No` VARCHAR(191) NULL,
    `End_No` VARCHAR(191) NULL,
    `Now_No` VARCHAR(191) NULL,
    `Total_M_Time` INTEGER NULL,
    `Total_P_Time` INTEGER NULL,
    `Re_Pr_Qty` INTEGER NULL,
    `Re_Total_M_Time` INTEGER NULL,
    `Re_Total_P_Time` INTEGER NULL,
    `Re_Total_N_Time` INTEGER NULL,
    `Re_Days` INTEGER NULL,
    `Re_Days_CAT` INTEGER NULL,
    `Re_Days_Work_R` INTEGER NULL,
    `Re_Days_Work_P` INTEGER NULL,
    `Re_Pr_Qty_P` INTEGER NULL,
    `Priority_P` INTEGER NULL,
    `Join_P` INTEGER NULL,
    `Priority_Rate` INTEGER NULL,
    `PPC1` VARCHAR(191) NULL,
    `PPC2` VARCHAR(191) NULL,
    `PPC3` VARCHAR(191) NULL,
    `PPC4` VARCHAR(191) NULL,
    `PPC5` VARCHAR(191) NULL,
    `PPC6` VARCHAR(191) NULL,
    `PPC7` VARCHAR(191) NULL,
    `PPC8` VARCHAR(191) NULL,
    `PPC9` VARCHAR(191) NULL,
    `PPC10` VARCHAR(191) NULL,
    `PPC11` VARCHAR(191) NULL,
    `PPC12` VARCHAR(191) NULL,
    `PPC13` VARCHAR(191) NULL,
    `PPC14` VARCHAR(191) NULL,
    `PPC15` VARCHAR(191) NULL,
    `PPC16` VARCHAR(191) NULL,
    `PPC17` VARCHAR(191) NULL,
    `PPC18` VARCHAR(191) NULL,
    `PPC19` VARCHAR(191) NULL,
    `PPC20` VARCHAR(191) NULL,
    `PPC21` VARCHAR(191) NULL,
    `PPC22` VARCHAR(191) NULL,
    `PPC23` VARCHAR(191) NULL,
    `PPC24` VARCHAR(191) NULL,
    `PPC25` VARCHAR(191) NULL,
    `PPC26` VARCHAR(191) NULL,
    `PPC27` VARCHAR(191) NULL,
    `PPC28` VARCHAR(191) NULL,
    `PPC29` VARCHAR(191) NULL,
    `PPC30` VARCHAR(191) NULL,
    `PPC31` VARCHAR(191) NULL,
    `PPC32` VARCHAR(191) NULL,
    `PPC33` VARCHAR(191) NULL,
    `PPC34` VARCHAR(191) NULL,
    `PPC35` VARCHAR(191) NULL,
    `PPC36` VARCHAR(191) NULL,
    `PMT1` INTEGER NULL,
    `PMT2` INTEGER NULL,
    `PMT3` INTEGER NULL,
    `PMT4` INTEGER NULL,
    `PMT5` INTEGER NULL,
    `PMT6` INTEGER NULL,
    `PMT7` INTEGER NULL,
    `PMT8` INTEGER NULL,
    `PMT9` INTEGER NULL,
    `PMT10` INTEGER NULL,
    `PMT11` INTEGER NULL,
    `PMT12` INTEGER NULL,
    `PMT13` INTEGER NULL,
    `PMT14` INTEGER NULL,
    `PMT15` INTEGER NULL,
    `PMT16` INTEGER NULL,
    `PMT17` INTEGER NULL,
    `PMT18` INTEGER NULL,
    `PMT19` INTEGER NULL,
    `PMT20` INTEGER NULL,
    `PMT21` INTEGER NULL,
    `PMT22` INTEGER NULL,
    `PMT23` INTEGER NULL,
    `PMT24` INTEGER NULL,
    `PMT25` INTEGER NULL,
    `PMT26` INTEGER NULL,
    `PMT27` INTEGER NULL,
    `PMT28` INTEGER NULL,
    `PMT29` INTEGER NULL,
    `PMT30` INTEGER NULL,
    `PMT31` INTEGER NULL,
    `PMT32` INTEGER NULL,
    `PMT33` INTEGER NULL,
    `PMT34` INTEGER NULL,
    `PMT35` INTEGER NULL,
    `PMT36` INTEGER NULL,

    PRIMARY KEY (`Order_No`, `Parts_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Result` (
    `Order_No` VARCHAR(191) NOT NULL,
    `Parts_No` VARCHAR(191) NOT NULL,
    `OdPt_No` VARCHAR(191) NULL,
    `Rs_Reg_Date` DATETIME(3) NULL,
    `Rs_Reg_Person_CD` VARCHAR(191) NULL,
    `Rs_Upd_Date` DATETIME(3) NULL,
    `Rs_Upd_Person_CD` VARCHAR(191) NULL,
    `RPC1` VARCHAR(191) NULL,
    `RPC2` VARCHAR(191) NULL,
    `RPC3` VARCHAR(191) NULL,
    `RPC4` VARCHAR(191) NULL,
    `RPC5` VARCHAR(191) NULL,
    `RPC6` VARCHAR(191) NULL,
    `RPC7` VARCHAR(191) NULL,
    `RPC8` VARCHAR(191) NULL,
    `RPC9` VARCHAR(191) NULL,
    `RPC10` VARCHAR(191) NULL,
    `RPC11` VARCHAR(191) NULL,
    `RPC12` VARCHAR(191) NULL,
    `RPC13` VARCHAR(191) NULL,
    `RPC14` VARCHAR(191) NULL,
    `RPC15` VARCHAR(191) NULL,
    `RPC16` VARCHAR(191) NULL,
    `RPC17` VARCHAR(191) NULL,
    `RPC18` VARCHAR(191) NULL,
    `RPC19` VARCHAR(191) NULL,
    `RPC20` VARCHAR(191) NULL,
    `RPC21` VARCHAR(191) NULL,
    `RPC22` VARCHAR(191) NULL,
    `RPC23` VARCHAR(191) NULL,
    `RPC24` VARCHAR(191) NULL,
    `RPC25` VARCHAR(191) NULL,
    `RPC26` VARCHAR(191) NULL,
    `RPC27` VARCHAR(191) NULL,
    `RPC28` VARCHAR(191) NULL,
    `RPC29` VARCHAR(191) NULL,
    `RPC30` VARCHAR(191) NULL,
    `RPC31` VARCHAR(191) NULL,
    `RPC32` VARCHAR(191) NULL,
    `RPC33` VARCHAR(191) NULL,
    `RPC34` VARCHAR(191) NULL,
    `RPC35` VARCHAR(191) NULL,
    `RPC36` VARCHAR(191) NULL,
    `RPD1` DATETIME(3) NULL,
    `RPD2` DATETIME(3) NULL,
    `RPD3` DATETIME(3) NULL,
    `RPD4` DATETIME(3) NULL,
    `RPD5` DATETIME(3) NULL,
    `RPD6` DATETIME(3) NULL,
    `RPD7` DATETIME(3) NULL,
    `RPD8` DATETIME(3) NULL,
    `RPD9` DATETIME(3) NULL,
    `RPD10` DATETIME(3) NULL,
    `RPD11` DATETIME(3) NULL,
    `RPD12` DATETIME(3) NULL,
    `RPD13` DATETIME(3) NULL,
    `RPD14` DATETIME(3) NULL,
    `RPD15` DATETIME(3) NULL,
    `RPD16` DATETIME(3) NULL,
    `RPD17` DATETIME(3) NULL,
    `RPD18` DATETIME(3) NULL,
    `RPD19` DATETIME(3) NULL,
    `RPD20` DATETIME(3) NULL,
    `RPD21` DATETIME(3) NULL,
    `RPD22` DATETIME(3) NULL,
    `RPD23` DATETIME(3) NULL,
    `RPD24` DATETIME(3) NULL,
    `RPD25` DATETIME(3) NULL,
    `RPD26` DATETIME(3) NULL,
    `RPD27` DATETIME(3) NULL,
    `RPD28` DATETIME(3) NULL,
    `RPD29` DATETIME(3) NULL,
    `RPD30` DATETIME(3) NULL,
    `RPD31` DATETIME(3) NULL,
    `RPD32` DATETIME(3) NULL,
    `RPD33` DATETIME(3) NULL,
    `RPD34` DATETIME(3) NULL,
    `RPD35` DATETIME(3) NULL,
    `RPD36` DATETIME(3) NULL,
    `RMT1` DOUBLE NULL,
    `RMT2` DOUBLE NULL,
    `RMT3` DOUBLE NULL,
    `RMT4` DOUBLE NULL,
    `RMT5` DOUBLE NULL,
    `RMT6` DOUBLE NULL,
    `RMT7` DOUBLE NULL,
    `RMT8` DOUBLE NULL,
    `RMT9` DOUBLE NULL,
    `RMT10` DOUBLE NULL,
    `RMT11` DOUBLE NULL,
    `RMT12` DOUBLE NULL,
    `RMT13` DOUBLE NULL,
    `RMT14` DOUBLE NULL,
    `RMT15` DOUBLE NULL,
    `RMT16` DOUBLE NULL,
    `RMT17` DOUBLE NULL,
    `RMT18` DOUBLE NULL,
    `RMT19` DOUBLE NULL,
    `RMT20` DOUBLE NULL,
    `RMT21` DOUBLE NULL,
    `RMT22` DOUBLE NULL,
    `RMT23` DOUBLE NULL,
    `RMT24` DOUBLE NULL,
    `RMT25` DOUBLE NULL,
    `RMT26` DOUBLE NULL,
    `RMT27` DOUBLE NULL,
    `RMT28` DOUBLE NULL,
    `RMT29` DOUBLE NULL,
    `RMT30` DOUBLE NULL,
    `RMT31` DOUBLE NULL,
    `RMT32` DOUBLE NULL,
    `RMT33` DOUBLE NULL,
    `RMT34` DOUBLE NULL,
    `RMT35` DOUBLE NULL,
    `RMT36` DOUBLE NULL,
    `RPT1` DOUBLE NULL,
    `RPT2` DOUBLE NULL,
    `RPT3` DOUBLE NULL,
    `RPT4` DOUBLE NULL,
    `RPT5` DOUBLE NULL,
    `RPT6` DOUBLE NULL,
    `RPT7` DOUBLE NULL,
    `RPT8` DOUBLE NULL,
    `RPT9` DOUBLE NULL,
    `RPT10` DOUBLE NULL,
    `RPT11` DOUBLE NULL,
    `RPT12` DOUBLE NULL,
    `RPT13` DOUBLE NULL,
    `RPT14` DOUBLE NULL,
    `RPT15` DOUBLE NULL,
    `RPT16` DOUBLE NULL,
    `RPT17` DOUBLE NULL,
    `RPT18` DOUBLE NULL,
    `RPT19` DOUBLE NULL,
    `RPT20` DOUBLE NULL,
    `RPT21` DOUBLE NULL,
    `RPT22` DOUBLE NULL,
    `RPT23` DOUBLE NULL,
    `RPT24` DOUBLE NULL,
    `RPT25` DOUBLE NULL,
    `RPT26` DOUBLE NULL,
    `RPT27` DOUBLE NULL,
    `RPT28` DOUBLE NULL,
    `RPT29` DOUBLE NULL,
    `RPT30` DOUBLE NULL,
    `RPT31` DOUBLE NULL,
    `RPT32` DOUBLE NULL,
    `RPT33` DOUBLE NULL,
    `RPT34` DOUBLE NULL,
    `RPT35` DOUBLE NULL,
    `RPT36` DOUBLE NULL,
    `RPN1` VARCHAR(191) NULL,
    `RPN2` VARCHAR(191) NULL,
    `RPN3` VARCHAR(191) NULL,
    `RPN4` VARCHAR(191) NULL,
    `RPN5` VARCHAR(191) NULL,
    `RPN6` VARCHAR(191) NULL,
    `RPN7` VARCHAR(191) NULL,
    `RPN8` VARCHAR(191) NULL,
    `RPN9` VARCHAR(191) NULL,
    `RPN10` VARCHAR(191) NULL,
    `RPN11` VARCHAR(191) NULL,
    `RPN12` VARCHAR(191) NULL,
    `RPN13` VARCHAR(191) NULL,
    `RPN14` VARCHAR(191) NULL,
    `RPN15` VARCHAR(191) NULL,
    `RPN16` VARCHAR(191) NULL,
    `RPN17` VARCHAR(191) NULL,
    `RPN18` VARCHAR(191) NULL,
    `RPN19` VARCHAR(191) NULL,
    `RPN20` VARCHAR(191) NULL,
    `RPN21` VARCHAR(191) NULL,
    `RPN22` VARCHAR(191) NULL,
    `RPN23` VARCHAR(191) NULL,
    `RPN24` VARCHAR(191) NULL,
    `RPN25` VARCHAR(191) NULL,
    `RPN26` VARCHAR(191) NULL,
    `RPN27` VARCHAR(191) NULL,
    `RPN28` VARCHAR(191) NULL,
    `RPN29` VARCHAR(191) NULL,
    `RPN30` VARCHAR(191) NULL,
    `RPN31` VARCHAR(191) NULL,
    `RPN32` VARCHAR(191) NULL,
    `RPN33` VARCHAR(191) NULL,
    `RPN34` VARCHAR(191) NULL,
    `RPN35` VARCHAR(191) NULL,
    `RPN36` VARCHAR(191) NULL,
    `Rs_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`Order_No`, `Parts_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Cost` (
    `Order_No` VARCHAR(191) NOT NULL,
    `Parts_No` VARCHAR(191) NOT NULL,
    `Cost_No` VARCHAR(191) NOT NULL,
    `Process_No` VARCHAR(191) NULL,
    `OdPt_No` VARCHAR(191) NULL,
    `OdPtCs_No` VARCHAR(191) NULL,
    `OdPtPr_No` VARCHAR(191) NULL,
    `CMC` VARCHAR(191) NULL,
    `CMT` VARCHAR(191) NULL,
    `CPC` VARCHAR(191) NULL,
    `CPT` VARCHAR(191) NULL,
    `CPD` VARCHAR(191) NULL,
    `CPN` VARCHAR(191) NULL,
    `Cs_Progress_CD` VARCHAR(191) NULL,
    `Cs_Complete_Date` DATETIME(3) NULL,
    `Cs_Complete_Qty` DOUBLE NULL,
    `Cs_Label_CSV` BOOLEAN NULL,
    `Cs_All_Complete` BOOLEAN NULL,
    `Cs_Order_All_Complete` BOOLEAN NULL,
    `Cs_Parts_Complete` BOOLEAN NULL,
    `Cs_Final_Complete` BOOLEAN NULL,
    `Cs_Modify_Date` DATETIME(3) NULL,
    `Cs_Remark` VARCHAR(191) NULL,
    `Cs_Register_Date` DATETIME(3) NULL,
    `Cs_Reg_Person_CD` VARCHAR(191) NULL,
    `Cs_Upd_Person_CD` VARCHAR(191) NULL,
    `Sequence_No` DOUBLE NULL,

    PRIMARY KEY (`Order_No`, `Parts_No`, `Cost_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_Schedule` (
    `Order_No` VARCHAR(191) NOT NULL,
    `Parts_No` VARCHAR(191) NOT NULL,
    `Schedule_No` VARCHAR(191) NULL,
    `Sc_Choice` VARCHAR(191) NULL,
    `Schedule_CD` VARCHAR(191) NULL,
    `Sc_Reg_Date` DATETIME(3) NULL,
    `Sc_Reg_Person_CD` VARCHAR(191) NULL,
    `Sc_Upd_Date` DATETIME(3) NULL,
    `Sc_Upd_Person_CD` VARCHAR(191) NULL,
    `PPD1` DATETIME(3) NULL,
    `PPD2` DATETIME(3) NULL,
    `PPD3` DATETIME(3) NULL,
    `PPD4` DATETIME(3) NULL,
    `PPD5` DATETIME(3) NULL,
    `PPD6` DATETIME(3) NULL,
    `PPD7` DATETIME(3) NULL,
    `PPD8` DATETIME(3) NULL,
    `PPD9` DATETIME(3) NULL,
    `PPD10` DATETIME(3) NULL,
    `PPD11` DATETIME(3) NULL,
    `PPD12` DATETIME(3) NULL,
    `PPD13` DATETIME(3) NULL,
    `PPD14` DATETIME(3) NULL,
    `PPD15` DATETIME(3) NULL,
    `PPD16` DATETIME(3) NULL,
    `PPD17` DATETIME(3) NULL,
    `PPD18` DATETIME(3) NULL,
    `PPD19` DATETIME(3) NULL,
    `PPD20` DATETIME(3) NULL,
    `PPD21` DATETIME(3) NULL,
    `PPD22` DATETIME(3) NULL,
    `PPD23` DATETIME(3) NULL,
    `PPD24` DATETIME(3) NULL,
    `PPD25` DATETIME(3) NULL,
    `PPD26` DATETIME(3) NULL,
    `PPD27` DATETIME(3) NULL,
    `PPD28` DATETIME(3) NULL,
    `PPD29` DATETIME(3) NULL,
    `PPD30` DATETIME(3) NULL,
    `PPD31` DATETIME(3) NULL,
    `PPD32` DATETIME(3) NULL,
    `PPD33` DATETIME(3) NULL,
    `PPD34` DATETIME(3) NULL,
    `PPD35` DATETIME(3) NULL,
    `PPD36` DATETIME(3) NULL,
    `PML1` DOUBLE NULL,
    `PML2` DOUBLE NULL,
    `PML3` DOUBLE NULL,
    `PML4` DOUBLE NULL,
    `PML5` DOUBLE NULL,
    `PML6` DOUBLE NULL,
    `PML7` DOUBLE NULL,
    `PML8` DOUBLE NULL,
    `PML9` DOUBLE NULL,
    `PML10` DOUBLE NULL,
    `PML11` DOUBLE NULL,
    `PML12` DOUBLE NULL,
    `PML13` DOUBLE NULL,
    `PML14` DOUBLE NULL,
    `PML15` DOUBLE NULL,
    `PML16` DOUBLE NULL,
    `PML17` DOUBLE NULL,
    `PML18` DOUBLE NULL,
    `PML19` DOUBLE NULL,
    `PML20` DOUBLE NULL,
    `PML21` DOUBLE NULL,
    `PML22` DOUBLE NULL,
    `PML23` DOUBLE NULL,
    `PML24` DOUBLE NULL,
    `PML25` DOUBLE NULL,
    `PML26` DOUBLE NULL,
    `PML27` DOUBLE NULL,
    `PML28` DOUBLE NULL,
    `PML29` DOUBLE NULL,
    `PML30` DOUBLE NULL,
    `PML31` DOUBLE NULL,
    `PML32` DOUBLE NULL,
    `PML33` DOUBLE NULL,
    `PML34` DOUBLE NULL,
    `PML35` DOUBLE NULL,
    `PML36` DOUBLE NULL,
    `PPL1` DOUBLE NULL,
    `PPL2` DOUBLE NULL,
    `PPL3` DOUBLE NULL,
    `PPL4` DOUBLE NULL,
    `PPL5` DOUBLE NULL,
    `PPL6` DOUBLE NULL,
    `PPL7` DOUBLE NULL,
    `PPL8` DOUBLE NULL,
    `PPL9` DOUBLE NULL,
    `PPL10` DOUBLE NULL,
    `PPL11` DOUBLE NULL,
    `PPL12` DOUBLE NULL,
    `PPL13` DOUBLE NULL,
    `PPL14` DOUBLE NULL,
    `PPL15` DOUBLE NULL,
    `PPL16` DOUBLE NULL,
    `PPL17` DOUBLE NULL,
    `PPL18` DOUBLE NULL,
    `PPL19` DOUBLE NULL,
    `PPL20` DOUBLE NULL,
    `PPL21` DOUBLE NULL,
    `PPL22` DOUBLE NULL,
    `PPL23` DOUBLE NULL,
    `PPL24` DOUBLE NULL,
    `PPL25` DOUBLE NULL,
    `PPL26` DOUBLE NULL,
    `PPL27` DOUBLE NULL,
    `PPL28` DOUBLE NULL,
    `PPL29` DOUBLE NULL,
    `PPL30` DOUBLE NULL,
    `PPL31` DOUBLE NULL,
    `PPL32` DOUBLE NULL,
    `PPL33` DOUBLE NULL,
    `PPL34` DOUBLE NULL,
    `PPL35` DOUBLE NULL,
    `PPL36` DOUBLE NULL,
    `ASP1` DATETIME(3) NULL,
    `ASP2` DATETIME(3) NULL,
    `ASP3` DATETIME(3) NULL,
    `ASP4` DATETIME(3) NULL,
    `ASP5` DATETIME(3) NULL,
    `ASP6` DATETIME(3) NULL,
    `ASP7` DATETIME(3) NULL,
    `ASP8` DATETIME(3) NULL,
    `ASP9` DATETIME(3) NULL,
    `ASP10` DATETIME(3) NULL,
    `ASP11` DATETIME(3) NULL,
    `ASP12` DATETIME(3) NULL,
    `ASP13` DATETIME(3) NULL,
    `ASP14` DATETIME(3) NULL,
    `ASP15` DATETIME(3) NULL,
    `ASP16` DATETIME(3) NULL,
    `ASP17` DATETIME(3) NULL,
    `ASP18` DATETIME(3) NULL,
    `ASP19` DATETIME(3) NULL,
    `ASP20` DATETIME(3) NULL,
    `ASP21` DATETIME(3) NULL,
    `ASP22` DATETIME(3) NULL,
    `ASP23` DATETIME(3) NULL,
    `ASP24` DATETIME(3) NULL,
    `ASP25` DATETIME(3) NULL,
    `ASP26` DATETIME(3) NULL,
    `ASP27` DATETIME(3) NULL,
    `ASP28` DATETIME(3) NULL,
    `ASP29` DATETIME(3) NULL,
    `ASP30` DATETIME(3) NULL,
    `ASP31` DATETIME(3) NULL,
    `ASP32` DATETIME(3) NULL,
    `ASP33` DATETIME(3) NULL,
    `ASP34` DATETIME(3) NULL,
    `ASP35` DATETIME(3) NULL,
    `ASP36` DATETIME(3) NULL,
    `BKD1` DATETIME(3) NULL,
    `BKD2` DATETIME(3) NULL,
    `BKD3` DATETIME(3) NULL,
    `BKD4` DATETIME(3) NULL,
    `BKD5` DATETIME(3) NULL,
    `BKD6` DATETIME(3) NULL,
    `BKD7` DATETIME(3) NULL,
    `BKD8` DATETIME(3) NULL,
    `BKD9` DATETIME(3) NULL,
    `BKD10` DATETIME(3) NULL,
    `BKD11` DATETIME(3) NULL,
    `BKD12` DATETIME(3) NULL,
    `BKD13` DATETIME(3) NULL,
    `BKD14` DATETIME(3) NULL,
    `BKD15` DATETIME(3) NULL,
    `BKD16` DATETIME(3) NULL,
    `BKD17` DATETIME(3) NULL,
    `BKD18` DATETIME(3) NULL,
    `BKD19` DATETIME(3) NULL,
    `BKD20` DATETIME(3) NULL,
    `BKD21` DATETIME(3) NULL,
    `BKD22` DATETIME(3) NULL,
    `BKD23` DATETIME(3) NULL,
    `BKD24` DATETIME(3) NULL,
    `BKD25` DATETIME(3) NULL,
    `BKD26` DATETIME(3) NULL,
    `BKD27` DATETIME(3) NULL,
    `BKD28` DATETIME(3) NULL,
    `BKD29` DATETIME(3) NULL,
    `BKD30` DATETIME(3) NULL,
    `BKD31` DATETIME(3) NULL,
    `BKD32` DATETIME(3) NULL,
    `BKD33` DATETIME(3) NULL,
    `BKD34` DATETIME(3) NULL,
    `BKD35` DATETIME(3) NULL,
    `BKD36` DATETIME(3) NULL,
    `INN1` VARCHAR(191) NULL,
    `INN2` VARCHAR(191) NULL,
    `INN3` VARCHAR(191) NULL,
    `INN4` VARCHAR(191) NULL,
    `INN5` VARCHAR(191) NULL,
    `INN6` VARCHAR(191) NULL,
    `INN7` VARCHAR(191) NULL,
    `INN8` VARCHAR(191) NULL,
    `INN9` VARCHAR(191) NULL,
    `INN10` VARCHAR(191) NULL,
    `INN11` VARCHAR(191) NULL,
    `INN12` VARCHAR(191) NULL,
    `INN13` VARCHAR(191) NULL,
    `INN14` VARCHAR(191) NULL,
    `INN15` VARCHAR(191) NULL,
    `INN16` VARCHAR(191) NULL,
    `INN17` VARCHAR(191) NULL,
    `INN18` VARCHAR(191) NULL,
    `INN19` VARCHAR(191) NULL,
    `INN20` VARCHAR(191) NULL,
    `INN21` VARCHAR(191) NULL,
    `INN22` VARCHAR(191) NULL,
    `INN23` VARCHAR(191) NULL,
    `INN24` VARCHAR(191) NULL,
    `INN25` VARCHAR(191) NULL,
    `INN26` VARCHAR(191) NULL,
    `INN27` VARCHAR(191) NULL,
    `INN28` VARCHAR(191) NULL,
    `INN29` VARCHAR(191) NULL,
    `INN30` VARCHAR(191) NULL,
    `INN31` VARCHAR(191) NULL,
    `INN32` VARCHAR(191) NULL,
    `INN33` VARCHAR(191) NULL,
    `INN34` VARCHAR(191) NULL,
    `INN35` VARCHAR(191) NULL,
    `INN36` VARCHAR(191) NULL,
    `As_FG` DOUBLE NULL,
    `As_Date` DATETIME(3) NULL,
    `As_Delivery` DATETIME(3) NULL,

    PRIMARY KEY (`Order_No`, `Parts_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TD_WIP` (
    `Order_No` VARCHAR(191) NOT NULL,
    `Parts_No` VARCHAR(191) NOT NULL,
    `Process_No` VARCHAR(191) NOT NULL,
    `OdPt_No` VARCHAR(191) NULL,
    `OdPtPr_No` VARCHAR(191) NULL,
    `PPG` VARCHAR(191) NULL,
    `PPC` VARCHAR(191) NULL,
    `PMT` DOUBLE NULL,
    `PPT` DOUBLE NULL,
    `T_Type` VARCHAR(191) NULL,
    `P_Type` VARCHAR(191) NULL,
    `S_Type` VARCHAR(191) NULL,
    `PPD` DATETIME(3) NULL,
    `PML` DOUBLE NULL,
    `PPL` DOUBLE NULL,
    `INN` DOUBLE NULL,
    `RPD` DOUBLE NULL,
    `RMT` DOUBLE NULL,
    `RPT` DOUBLE NULL,
    `RPN` DOUBLE NULL,
    `ASP` DOUBLE NULL,
    `Now_No` VARCHAR(191) NULL,
    `WIP_CAT1` BOOLEAN NULL,
    `WIP_CAT2` BOOLEAN NULL,
    `WIP_CAT3` BOOLEAN NULL,
    `WIP_CAT4` BOOLEAN NULL,
    `WIP_CAT5` BOOLEAN NULL,
    `WIP_CAT6` BOOLEAN NULL,
    `WIP_CAT7` BOOLEAN NULL,
    `WIP_CAT8` BOOLEAN NULL,
    `WIP_CAT9` BOOLEAN NULL,
    `WIP_Month_Plan` BOOLEAN NULL,
    `WIP_Week_Plan` BOOLEAN NULL,
    `WIP_Today_Plan` BOOLEAN NULL,
    `Plan_Person_CD` VARCHAR(191) NULL,
    `WIP_Remark` VARCHAR(191) NULL,
    `Into_I` BOOLEAN NULL,

    PRIMARY KEY (`Order_No`, `Parts_No`, `Process_No`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_Process` (
    `Process_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NULL,
    `ProcessG_CD` VARCHAR(191) NOT NULL,
    `ResourceG_CD` VARCHAR(191) NOT NULL,
    `ManageG_CD` VARCHAR(191) NULL,
    `Manhour_Calc` VARCHAR(191) NULL,
    `Days_Calc` VARCHAR(191) NULL,
    `Process_Name` VARCHAR(191) NULL,
    `Process_Abb` VARCHAR(191) NULL,
    `Process_Symbol` VARCHAR(191) NULL,
    `Process_Mark` VARCHAR(191) NULL,
    `Use` VARCHAR(191) NULL,
    `For_Plan` VARCHAR(191) NULL,
    `For_Info` VARCHAR(191) NULL,
    `Graph` VARCHAR(191) NULL,
    `List` VARCHAR(191) NULL,
    `Outside_On` VARCHAR(191) NULL,
    `Outside_Off` VARCHAR(191) NULL,
    `End` VARCHAR(191) NULL,
    `Coefficient` VARCHAR(191) NULL,
    `M_Coefficient` VARCHAR(191) NULL,
    `P_Coefficient` VARCHAR(191) NULL,
    `Before` VARCHAR(191) NULL,
    `After` DOUBLE NULL,
    `Operation_Time` DOUBLE NULL,
    `Std_M_CAT` DOUBLE NULL,
    `Std_M_Time` DOUBLE NULL,
    `Std_P_CAT` DOUBLE NULL,
    `Std_P_Time` DOUBLE NULL,
    `T_Type` VARCHAR(191) NULL,
    `P_Type` VARCHAR(191) NULL,
    `S_Type` VARCHAR(191) NULL,
    `Process_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`Process_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_ProcessG` (
    `ProcessG_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NULL,
    `ManageG_CD` VARCHAR(191) NULL,
    `ProcessG_Name` VARCHAR(191) NULL,
    `ProcessG_Abb` VARCHAR(191) NULL,
    `ProcessG_Symbol` VARCHAR(191) NULL,
    `ProcessG_Mark` VARCHAR(191) NULL,
    `Use` VARCHAR(191) NULL,
    `Use_Object` VARCHAR(191) NULL,
    `Graph` VARCHAR(191) NULL,
    `List` VARCHAR(191) NULL,
    `Coefficient` VARCHAR(191) NULL,
    `M_Coefficient` VARCHAR(191) NULL,
    `P_Coefficient` VARCHAR(191) NULL,
    `Std_M_CAT` VARCHAR(191) NULL,
    `Std_M_Time` DOUBLE NULL,
    `Std_P_CAT` DOUBLE NULL,
    `Std_P_Time` DOUBLE NULL,
    `M_Resource_N` DOUBLE NULL,
    `S_Resource_N` DOUBLE NULL,
    `ProcessG_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`ProcessG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_ResourceG` (
    `ResourceG_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NULL,
    `ResourceG_Name` VARCHAR(191) NULL,
    `ResourceG_Abb` VARCHAR(191) NULL,
    `ResourceG_Symbol` VARCHAR(191) NULL,
    `ResourceG_Mark` VARCHAR(191) NULL,
    `Us_Group_Mark` VARCHAR(191) NULL,
    `Use` VARCHAR(191) NULL,
    `Coefficient` DOUBLE NULL,
    `M_Coefficient` DOUBLE NULL,
    `P_Coefficient` DOUBLE NULL,
    `M_Resource_Object` VARCHAR(191) NULL,
    `S_Resource_Object` VARCHAR(191) NULL,
    `ResourceG_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`ResourceG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_Resource` (
    `Resource_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NULL,
    `ResourceG_CD` VARCHAR(191) NULL,
    `CostG_CD` VARCHAR(191) NULL,
    `ManageG_CD` VARCHAR(191) NULL,
    `Resource_Name` VARCHAR(191) NULL,
    `Resource_Abb` VARCHAR(191) NULL,
    `Resource_Symbol` VARCHAR(191) NULL,
    `Resource_Mark` VARCHAR(191) NULL,
    `Use` VARCHAR(191) NULL,
    `End` VARCHAR(191) NULL,
    `M_Coefficient` VARCHAR(191) NULL,
    `P_Coefficient` DOUBLE NULL,
    `Before` DOUBLE NULL,
    `After` DOUBLE NULL,
    `T_Type` VARCHAR(191) NULL,
    `P_Type` VARCHAR(191) NULL,
    `Resource_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`Resource_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_CostG` (
    `CostG_CD` VARCHAR(191) NOT NULL,
    `Change_CD` VARCHAR(191) NULL,
    `CostG_Name` VARCHAR(191) NULL,
    `CostG_Abb` VARCHAR(191) NULL,
    `CostG_Symbol` VARCHAR(191) NULL,
    `CostG_Mark` VARCHAR(191) NULL,
    `Use` VARCHAR(191) NULL,
    `Coefficient` VARCHAR(191) NULL,
    `M_Coefficient` VARCHAR(191) NULL,
    `P_Coefficient` DOUBLE NULL,
    `CostG_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`CostG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_WorkG` (
    `WorkG_CD` VARCHAR(191) NOT NULL,
    `WorkG_Name` VARCHAR(191) NULL,
    `WorkG_Abb` VARCHAR(191) NULL,
    `WorkG_Symbol` VARCHAR(191) NULL,
    `Pl_Object_Grp` VARCHAR(191) NULL,
    `Pl_Object` BOOLEAN NULL,
    `Target_Amount` DOUBLE NULL,
    `WorkG_Mark` VARCHAR(191) NULL,

    PRIMARY KEY (`WorkG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_Worker` (
    `Worker_CD` VARCHAR(191) NOT NULL,
    `Worker_Pass` VARCHAR(191) NULL,
    `WorkerG_CD` VARCHAR(191) NULL,
    `WorkG_CD` VARCHAR(191) NOT NULL,
    `Worker_Name` VARCHAR(191) NULL,
    `Worker_Abb` VARCHAR(191) NULL,
    `Worker_JPN` VARCHAR(191) NULL,
    `Access_Lv` INTEGER NULL,
    `Worker_Level` VARCHAR(191) NULL,
    `Worker_Menu` VARCHAR(191) NULL,
    `Worker_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`Worker_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_WorkerG` (
    `WorkerG_CD` VARCHAR(191) NOT NULL,
    `WorkerG_Name` VARCHAR(191) NULL,
    `WorkerG_Abb` VARCHAR(191) NULL,
    `WorkerG_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`WorkerG_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_Customer` (
    `Customer_CD` VARCHAR(191) NOT NULL,
    `Customer_Name` VARCHAR(191) NULL,
    `Customer_Name2` VARCHAR(191) NULL,
    `Customer_Abb` VARCHAR(191) NULL,
    `Customer_Add` VARCHAR(191) NULL,
    `Customer_Add2` VARCHAR(191) NULL,
    `Customer_Add3` VARCHAR(191) NULL,
    `Customer_Contact` VARCHAR(191) NULL,
    `Customer_TEL` VARCHAR(191) NULL,
    `Posting_Group` VARCHAR(191) NULL,
    `Payment_CD` VARCHAR(191) NULL,
    `Sl_Person_CD` VARCHAR(191) NULL,
    `Blocked` BOOLEAN NOT NULL,
    `Customer_FAX` VARCHAR(191) NULL,
    `Branch_No` VARCHAR(191) NULL,
    `Nationality` VARCHAR(191) NULL,
    `Customer_Group` VARCHAR(191) NULL,
    `VAT_Reg_No` VARCHAR(191) NULL,
    `Customer_Remark` VARCHAR(191) NULL,

    PRIMARY KEY (`Customer_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TS_Set` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `Use` BOOLEAN NULL,
    `Version` TEXT NULL,
    `Field_Name` TEXT NULL,
    `Data_Type` TEXT NULL,
    `AutoNumber` BOOLEAN NULL,
    `Password` TEXT NULL,
    `Language` TEXT NULL,
    `Od_No_Digits` INTEGER NULL,
    `SV_Name` TEXT NULL,
    `TENKEI` TEXT NULL,
    `Sales_Docu` TEXT NULL,
    `Sales_Docu_Type` TEXT NULL,
    `Product_Docu` TEXT NULL,
    `Product_Docu_Type` TEXT NULL,
    `Procure_Docu` TEXT NULL,
    `Procure_Docu_Type` TEXT NULL,
    `Outside_Docu` TEXT NULL,
    `Outside_Docu_Type` TEXT NULL,
    `Inspect_Docu` TEXT NULL,
    `Inspect_Docu_Type` TEXT NULL,
    `Send_Docu` TEXT NULL,
    `Send_Docu_Type` TEXT NULL,
    `Supple_Docu` TEXT NULL,
    `Supple_Docu_Type` TEXT NULL,
    `SOrder_CSV` TEXT NULL,
    `SOrder_CSV_BK` TEXT NULL,
    `SOrder_CSV_CP` TEXT NULL,
    `Order_CSV` TEXT NULL,
    `Order_CSV_BK` TEXT NULL,
    `Order_CSV_CP` TEXT NULL,
    `Procure_CSV` TEXT NULL,
    `Procure_CSV_BK` TEXT NULL,
    `Procure_CSV_CP` TEXT NULL,
    `Cost_CSV` TEXT NULL,
    `WIP_CSV` TEXT NULL,
    `WIP_CSV_Writing` TEXT NULL,
    `Cost_Save` TEXT NULL,
    `Cost_Save_Time` DATETIME(3) NULL,
    `Cost_Write` TEXT NULL,
    `Cost_Write_Time` DATETIME(3) NULL,
    `Delivery_CSV` TEXT NULL,
    `Label_CSV` TEXT NULL,
    `Label_CSV_FG` BOOLEAN NULL,
    `ASPROVA` TEXT NULL,
    `As_Operation_Csv` TEXT NULL,
    `As_Resource_Csv` TEXT NULL,
    `As_Plan_Csv` TEXT NULL,
    `As_Use_Csv` TEXT NULL,
    `As_Input_Csv` TEXT NULL,
    `As_Schedule_Csv` TEXT NULL,
    `Us_Group_CD` TEXT NULL,
    `Us_Group_Name` TEXT NULL,
    `Us_Group_Abb` TEXT NULL,
    `Us_Group_Symbol` TEXT NULL,
    `Us_Group_Mark` TEXT NULL,
    `Us_Group_TEL` TEXT NULL,
    `Us_Group_FAX` TEXT NULL,
    `Us_Office_CD` TEXT NULL,
    `Us_Office_Name` TEXT NULL,
    `Us_Office_Abb` TEXT NULL,
    `Us_Office_Symbol` TEXT NULL,
    `Us_Office_Mark` TEXT NULL,
    `St_Target_Week1` DATETIME(3) NULL,
    `Ed_Target_Week1` DATETIME(3) NULL,
    `St_Target_Week2` DATETIME(3) NULL,
    `Ed_Target_Week2` DATETIME(3) NULL,
    `Ed_Target_Week3` DATETIME(3) NULL,
    `St_Target_Week4` DATETIME(3) NULL,
    `Ed_Target_Week4` DATETIME(3) NULL,
    `St_Target_Week5` DATETIME(3) NULL,
    `Ed_Target_Week5` DATETIME(3) NULL,
    `Od_DrawNo_Reflect` BOOLEAN NULL,
    `PI_Quote_Delivery` TEXT NULL,
    `Pl_Abst_St_Days` INTEGER NULL,
    `Pl_Abst_Ed_Days` INTEGER NULL,
    `Sc_Make_Type` TEXT NULL,
    `Sc_Stagnat_Time` INTEGER NULL,
    `Sc_Stagnat_Scale` INTEGER NULL,
    `Sc_Person_Scale` INTEGER NULL,
    `Sc_Machine_Scale` INTEGER NULL,
    `Sc_Outside_Scale` INTEGER NULL,
    `Sc_ManHour_Scale` INTEGER NULL,
    `Ps_Delivery1` TEXT NULL,
    `Ps_Delivery2` TEXT NULL,
    `Ps_Delivery3` TEXT NULL,
    `Ps_Delivery4` TEXT NULL,
    `Ps_Draw_No_View` BOOLEAN NULL,
    `Ps_Entry_Text1` TEXT NULL,
    `Ps_Entry_Text2` TEXT NULL,
    `Ps_Entry_Text3` TEXT NULL,
    `Ps_Under_Text` TEXT NULL,
    `Rs_BarCode_Input` BOOLEAN NULL,
    `Rs_Move_Range` TEXT NULL,
    `Rs_Time_Input` BOOLEAN NULL,
    `Rs_Auto_Finish` BOOLEAN NULL,
    `Od_List_ViewW` INTEGER NULL,
    `Pc_List_ViewW` INTEGER NULL,
    `Pc_List_ViewH` INTEGER NULL,
    `Pl_List_ViewW` INTEGER NULL,
    `Pl_List_ViewH` INTEGER NULL,
    `Rs_List_ViewH` INTEGER NULL,
    `Od_Search_ViewW` INTEGER NULL,
    `Od_Search_ViewH` INTEGER NULL,
    `Pl_Search_ViewW` INTEGER NULL,
    `Pl_Search_ViewH` INTEGER NULL,
    `PI_Change_Page` TEXT NULL,
    `PI_Schedule` TEXT NULL,
    `Pl_Color_Separate` BOOLEAN NULL,
    `PI_Delivery1` TEXT NULL,
    `Pl_Delivery2` TEXT NULL,
    `Pl_Delivery3` TEXT NULL,
    `Job_Find_St_Days` INTEGER NULL,
    `Job_Find_Ed_Days` INTEGER NULL,
    `Settles` BOOLEAN NULL,
    `Settles_Day` DATETIME(3) NULL,
    `Pd_Revision_Days` INTEGER NULL,
    `Od_Sach_S_Years` INTEGER NULL,
    `PI_Sach_S_Years` INTEGER NULL,
    `LINK_Name1` TEXT NULL,
    `LINK1` TEXT NULL,
    `LINK_Name2` TEXT NULL,
    `LINK2` TEXT NULL,
    `LINK_Name3` TEXT NULL,
    `LINK3` TEXT NULL,
    `LINK_Name4` TEXT NULL,
    `LINK4` TEXT NULL,
    `LINK_Name5` TEXT NULL,
    `LINK5` TEXT NULL,
    `LINK_Name6` TEXT NULL,
    `LINK6` TEXT NULL,
    `LINK_Name7` TEXT NULL,
    `LINK7` TEXT NULL,
    `LINK_Name8` TEXT NULL,
    `LINK8` TEXT NULL,
    `LINK_Name9` TEXT NULL,
    `LINK9` TEXT NULL,
    `LINK_Name10` TEXT NULL,
    `LINK10` TEXT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_request1` (
    `Request1_CD` VARCHAR(2) NOT NULL,
    `Request1_Name` VARCHAR(20) NULL,
    `Request1_Abb` VARCHAR(10) NULL,
    `Request1_Symbol` VARCHAR(10) NULL,
    `Request1_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Request1_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_request2` (
    `Request2_CD` VARCHAR(2) NOT NULL,
    `Request2_Name` VARCHAR(20) NULL,
    `Request2_Abb` VARCHAR(10) NULL,
    `Request2_Symbol` VARCHAR(10) NULL,
    `Request2_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Request2_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_request3` (
    `Request3_CD` VARCHAR(2) NOT NULL,
    `Request3_Name` VARCHAR(20) NULL,
    `Request3_Abb` VARCHAR(10) NULL,
    `Request3_Symbol` VARCHAR(10) NULL,
    `Request3_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Request3_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_target` (
    `Target_CD` VARCHAR(2) NOT NULL,
    `Target_Name` VARCHAR(10) NULL,
    `Target_Abb` VARCHAR(5) NULL,
    `Target_Symbol` VARCHAR(5) NULL,
    `Target_Mark` VARCHAR(5) NULL,
    `Target_Price` DOUBLE NULL,
    `Target_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Target_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_unit` (
    `Unit_CD` VARCHAR(2) NOT NULL,
    `Unit_Name` VARCHAR(50) NULL,
    `Unit_Abb` VARCHAR(50) NULL,
    `Unit_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Unit_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_supply` (
    `Supply_CD` VARCHAR(2) NOT NULL,
    `Supply_Name` VARCHAR(20) NULL,
    `Supply_Abb` VARCHAR(15) NULL,
    `Supply_Symbol` VARCHAR(10) NULL,
    `Supply_Mark` VARCHAR(10) NULL,
    `Supply_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Supply_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_item1` (
    `Item1_CD` VARCHAR(20) NOT NULL,
    `Item1_Name` VARCHAR(50) NULL,
    `Item1_Name2` VARCHAR(50) NULL,
    `Item1_Abb` VARCHAR(50) NULL,
    `Item1_Unit` VARCHAR(10) NULL,
    `Posting_Group` VARCHAR(10) NULL,
    `Unit_Price` DECIMAL(28, 20) NULL,
    `Unit_Cost` DECIMAL(28, 20) NULL,
    `Gross_Weight` DECIMAL(28, 20) NULL,
    `Net_Weight` DECIMAL(28, 20) NULL,
    `Blocked` BIT(1) NULL,
    `Item1_Type` VARCHAR(20) NULL,
    `Item1_Grp` VARCHAR(50) NULL,
    `Item1_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Item1_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_coating` (
    `Coating_CD` VARCHAR(2) NOT NULL,
    `Coating_Name` VARCHAR(10) NULL,
    `Coating_Abb` VARCHAR(5) NULL,
    `Coating_Symbol` VARCHAR(3) NULL,
    `Coating_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Coating_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_price` (
    `Price_CD` VARCHAR(2) NOT NULL,
    `Price_Name` VARCHAR(15) NULL,
    `Price_Abb` VARCHAR(10) NULL,
    `Price_Symbol` VARCHAR(5) NULL,
    `Price_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Price_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_contract_docu` (
    `Contract_Docu_CD` VARCHAR(6) NOT NULL,
    `Contract_Docu_Name` VARCHAR(10) NULL,
    `Contract_Docu_Abb` VARCHAR(10) NULL,
    `Contract_Docu_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Contract_Docu_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_od_quote` (
    `Od_Quote_CD` VARCHAR(2) NOT NULL,
    `Od_Quote_Name` VARCHAR(15) NULL,
    `Od_Quote_Abb` VARCHAR(10) NULL,
    `Od_Quote_Symbol` VARCHAR(5) NULL,
    `Od_Quote_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Od_Quote_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_od_progress` (
    `Od_Progress_CD` VARCHAR(2) NOT NULL,
    `Od_Progress_Name` VARCHAR(20) NULL,
    `Od_Progress_Abb` VARCHAR(10) NULL,
    `Od_Progress_Symbol` VARCHAR(5) NULL,
    `Od_Progress_Mark` VARCHAR(5) NULL,
    `Od_Progress_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Od_Progress_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_delivery` (
    `Delivery_CD` VARCHAR(2) NOT NULL,
    `Delivery_Name` VARCHAR(30) NULL,
    `Delivery_Abb` VARCHAR(25) NULL,
    `Delivery_Symbol` VARCHAR(20) NULL,
    `Delivery_Mark` VARCHAR(15) NULL,
    `Coefficient` DOUBLE NULL,
    `For_Order` BIT(1) NULL,
    `For_Procure` BIT(1) NULL,
    `Delivery_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Delivery_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_specific` (
    `Specific_CD` VARCHAR(2) NOT NULL,
    `Specific_Name` VARCHAR(20) NULL,
    `Specific_Abb` VARCHAR(15) NULL,
    `Specific_Symbol` VARCHAR(10) NULL,
    `Specific_Mark` VARCHAR(5) NULL,
    `Specific_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`Specific_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_pc_progress` (
    `Pc_Progress_CD` VARCHAR(2) NOT NULL,
    `Pc_Progress_Name` VARCHAR(25) NULL,
    `Pc_Progress_Abb` VARCHAR(15) NULL,
    `Pc_Progress_Symbol` VARCHAR(5) NULL,
    `Pc_Progress_Mark` VARCHAR(5) NULL,
    `Pc_Progress_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Pc_Progress_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_inoutside` (
    `InOutside_CD` VARCHAR(2) NOT NULL,
    `InOutside_Name` VARCHAR(5) NULL,
    `InOutside_Abb` VARCHAR(5) NULL,
    `InOutside_Symbol` VARCHAR(5) NULL,
    `InOutside_Mark` VARCHAR(5) NULL,
    `InOutside_Remark` VARCHAR(20) NULL,

    PRIMARY KEY (`InOutside_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tm_vendor` (
    `Vendor_CD` VARCHAR(20) NOT NULL,
    `Vendor_Name` VARCHAR(50) NULL,
    `Vendor_Name2` VARCHAR(50) NULL,
    `Vendor_Abb` VARCHAR(50) NULL,
    `Vendor_Add` VARCHAR(50) NULL,
    `Vendor_Add2` VARCHAR(50) NULL,
    `Vendor_Add3` VARCHAR(50) NULL,
    `Vendor_Contact` VARCHAR(50) NULL,
    `Vendor_TEL` VARCHAR(30) NULL,
    `Posting_Group` VARCHAR(10) NULL,
    `Payment_CD` VARCHAR(10) NULL,
    `Blocked` BIT(1) NULL,
    `VAT_Reg_No` VARCHAR(20) NULL,
    `Branch_No` VARCHAR(5) NULL,
    `Nationality` VARCHAR(30) NULL,
    `Vendor_Group` VARCHAR(30) NULL,
    `Vendor_Remark` VARCHAR(50) NULL,

    PRIMARY KEY (`Vendor_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TM_User` (
    `User_ID` VARCHAR(191) NOT NULL,
    `User_Name` VARCHAR(191) NULL,
    `User_Abb` VARCHAR(191) NULL,
    `User_Pass` VARCHAR(191) NULL,
    `User_Remark` VARCHAR(191) NULL,
    `F0100` BOOLEAN NULL DEFAULT false,
    `F0101` BOOLEAN NULL DEFAULT false,
    `F0102` BOOLEAN NULL DEFAULT false,
    `F0103` BOOLEAN NULL DEFAULT false,
    `F0104` BOOLEAN NULL DEFAULT false,
    `F0105` BOOLEAN NULL DEFAULT false,
    `F0106` BOOLEAN NULL DEFAULT false,
    `F0107` BOOLEAN NULL DEFAULT false,
    `F0108` BOOLEAN NULL DEFAULT false,
    `F0109` BOOLEAN NULL DEFAULT false,
    `F0110` BOOLEAN NULL DEFAULT false,
    `F0112` BOOLEAN NULL DEFAULT false,
    `F0113` BOOLEAN NULL DEFAULT false,
    `F0114` BOOLEAN NULL DEFAULT false,
    `F0115` BOOLEAN NULL DEFAULT false,
    `F0116` BOOLEAN NULL DEFAULT false,
    `F0117` BOOLEAN NULL DEFAULT false,
    `F0118` BOOLEAN NULL DEFAULT false,
    `F0119` BOOLEAN NULL DEFAULT false,
    `F0120` BOOLEAN NULL DEFAULT false,
    `F0200` BOOLEAN NULL DEFAULT false,
    `F0201` BOOLEAN NULL DEFAULT false,
    `F0202` BOOLEAN NULL DEFAULT false,
    `F0203` BOOLEAN NULL DEFAULT false,
    `F0204` BOOLEAN NULL DEFAULT false,
    `F0205` BOOLEAN NULL DEFAULT false,
    `F0206` BOOLEAN NULL DEFAULT false,
    `F0207` BOOLEAN NULL DEFAULT false,
    `F0208` BOOLEAN NULL DEFAULT false,
    `F0209` BOOLEAN NULL DEFAULT false,
    `F0210` BOOLEAN NULL DEFAULT false,
    `F0211` BOOLEAN NULL DEFAULT false,
    `F0212` BOOLEAN NULL DEFAULT false,
    `F0213` BOOLEAN NULL DEFAULT false,
    `F0214` BOOLEAN NULL DEFAULT false,
    `F0215` BOOLEAN NULL DEFAULT false,
    `F0216` BOOLEAN NULL DEFAULT false,
    `F0217` BOOLEAN NULL DEFAULT false,
    `F0218` BOOLEAN NULL DEFAULT false,
    `F0219` BOOLEAN NULL DEFAULT false,
    `F0220` BOOLEAN NULL DEFAULT false,
    `F0300` BOOLEAN NULL DEFAULT false,
    `F0301` BOOLEAN NULL DEFAULT false,
    `F0302` BOOLEAN NULL DEFAULT false,
    `F0303` BOOLEAN NULL DEFAULT false,
    `F0304` BOOLEAN NULL DEFAULT false,
    `F0305` BOOLEAN NULL DEFAULT false,
    `F0306` BOOLEAN NULL DEFAULT false,
    `F0307` BOOLEAN NULL DEFAULT false,
    `F0308` BOOLEAN NULL DEFAULT false,
    `F0309` BOOLEAN NULL DEFAULT false,
    `F0310` BOOLEAN NULL DEFAULT false,
    `F0311` BOOLEAN NULL DEFAULT false,
    `F0312` BOOLEAN NULL DEFAULT false,
    `F0313` BOOLEAN NULL DEFAULT false,
    `F0314` BOOLEAN NULL DEFAULT false,
    `F0315` BOOLEAN NULL DEFAULT false,
    `F0316` BOOLEAN NULL DEFAULT false,
    `F0317` BOOLEAN NULL DEFAULT false,
    `F0318` BOOLEAN NULL DEFAULT false,
    `F0319` BOOLEAN NULL DEFAULT false,
    `F0320` BOOLEAN NULL DEFAULT false,
    `F0400` BOOLEAN NULL DEFAULT false,
    `F0401` BOOLEAN NULL DEFAULT false,
    `F0402` BOOLEAN NULL DEFAULT false,
    `F0403` BOOLEAN NULL DEFAULT false,
    `F0404` BOOLEAN NULL DEFAULT false,
    `F0405` BOOLEAN NULL DEFAULT false,
    `F0406` BOOLEAN NULL DEFAULT false,
    `F0407` BOOLEAN NULL DEFAULT false,
    `F0408` BOOLEAN NULL DEFAULT false,
    `F0409` BOOLEAN NULL DEFAULT false,
    `F0410` BOOLEAN NULL DEFAULT false,
    `F0411` BOOLEAN NULL DEFAULT false,
    `F0412` BOOLEAN NULL DEFAULT false,
    `F0413` BOOLEAN NULL DEFAULT false,
    `F0414` BOOLEAN NULL DEFAULT false,
    `F0415` BOOLEAN NULL DEFAULT false,
    `F0416` BOOLEAN NULL DEFAULT false,
    `F0417` BOOLEAN NULL DEFAULT false,
    `F0418` BOOLEAN NULL DEFAULT false,
    `F0419` BOOLEAN NULL DEFAULT false,
    `F0420` BOOLEAN NULL DEFAULT false,
    `F0500` BOOLEAN NULL DEFAULT false,
    `F0501` BOOLEAN NULL DEFAULT false,
    `F0502` BOOLEAN NULL DEFAULT false,
    `F0503` BOOLEAN NULL DEFAULT false,
    `F0504` BOOLEAN NULL DEFAULT false,
    `F0505` BOOLEAN NULL DEFAULT false,
    `F0506` BOOLEAN NULL DEFAULT false,
    `F0507` BOOLEAN NULL DEFAULT false,
    `F0508` BOOLEAN NULL DEFAULT false,
    `F0509` BOOLEAN NULL DEFAULT false,
    `F0510` BOOLEAN NULL DEFAULT false,
    `F0511` BOOLEAN NULL DEFAULT false,
    `F0512` BOOLEAN NULL DEFAULT false,
    `F0513` BOOLEAN NULL DEFAULT false,
    `F0514` BOOLEAN NULL DEFAULT false,
    `F0515` BOOLEAN NULL DEFAULT false,
    `F0516` BOOLEAN NULL DEFAULT false,
    `F0517` BOOLEAN NULL DEFAULT false,
    `F0518` BOOLEAN NULL DEFAULT false,
    `F0519` BOOLEAN NULL DEFAULT false,
    `F0520` BOOLEAN NULL DEFAULT false,
    `F0600` BOOLEAN NULL DEFAULT false,
    `F0601` BOOLEAN NULL DEFAULT false,
    `F0602` BOOLEAN NULL DEFAULT false,
    `F0603` BOOLEAN NULL DEFAULT false,
    `F0604` BOOLEAN NULL DEFAULT false,
    `F0605` BOOLEAN NULL DEFAULT false,
    `F0606` BOOLEAN NULL DEFAULT false,
    `F0607` BOOLEAN NULL DEFAULT false,
    `F0608` BOOLEAN NULL DEFAULT false,
    `F0609` BOOLEAN NULL DEFAULT false,
    `F0610` BOOLEAN NULL DEFAULT false,
    `F0611` BOOLEAN NULL DEFAULT false,
    `F0612` BOOLEAN NULL DEFAULT false,
    `F0613` BOOLEAN NULL DEFAULT false,
    `F0614` BOOLEAN NULL DEFAULT false,
    `F0615` BOOLEAN NULL DEFAULT false,
    `F0616` BOOLEAN NULL DEFAULT false,
    `F0617` BOOLEAN NULL DEFAULT false,
    `F0618` BOOLEAN NULL DEFAULT false,
    `F0619` BOOLEAN NULL DEFAULT false,
    `F0620` BOOLEAN NULL DEFAULT false,
    `F0700` BOOLEAN NULL DEFAULT false,
    `F0701` BOOLEAN NULL DEFAULT false,
    `F0702` BOOLEAN NULL DEFAULT false,
    `F0703` BOOLEAN NULL DEFAULT false,
    `F0704` BOOLEAN NULL DEFAULT false,
    `F0705` BOOLEAN NULL DEFAULT false,
    `F0706` BOOLEAN NULL DEFAULT false,
    `F0707` BOOLEAN NULL DEFAULT false,
    `F0708` BOOLEAN NULL DEFAULT false,
    `F0709` BOOLEAN NULL DEFAULT false,
    `F0710` BOOLEAN NULL DEFAULT false,
    `F0711` BOOLEAN NULL DEFAULT false,
    `F0712` BOOLEAN NULL DEFAULT false,
    `F0713` BOOLEAN NULL DEFAULT false,
    `F0714` BOOLEAN NULL DEFAULT false,
    `F0715` BOOLEAN NULL DEFAULT false,
    `F0716` BOOLEAN NULL DEFAULT false,
    `F0717` BOOLEAN NULL DEFAULT false,
    `F0718` BOOLEAN NULL DEFAULT false,
    `F0719` BOOLEAN NULL DEFAULT false,
    `F0720` BOOLEAN NULL DEFAULT false,
    `F0800` BOOLEAN NULL DEFAULT false,
    `F0801` BOOLEAN NULL DEFAULT false,
    `F0802` BOOLEAN NULL DEFAULT false,
    `F0803` BOOLEAN NULL DEFAULT false,
    `F0804` BOOLEAN NULL DEFAULT false,
    `F0805` BOOLEAN NULL DEFAULT false,
    `F0806` BOOLEAN NULL DEFAULT false,
    `F0807` BOOLEAN NULL DEFAULT false,
    `F0808` BOOLEAN NULL DEFAULT false,
    `F0809` BOOLEAN NULL DEFAULT false,
    `F0810` BOOLEAN NULL DEFAULT false,
    `F0811` BOOLEAN NULL DEFAULT false,
    `F0812` BOOLEAN NULL DEFAULT false,
    `F0813` BOOLEAN NULL DEFAULT false,
    `F0814` BOOLEAN NULL DEFAULT false,
    `F0815` BOOLEAN NULL DEFAULT false,
    `F0816` BOOLEAN NULL DEFAULT false,
    `F0817` BOOLEAN NULL DEFAULT false,
    `F0818` BOOLEAN NULL DEFAULT false,
    `F0819` BOOLEAN NULL DEFAULT false,
    `F0820` BOOLEAN NULL DEFAULT false,
    `F0900` BOOLEAN NULL DEFAULT false,
    `F0901` BOOLEAN NULL DEFAULT false,
    `F0902` BOOLEAN NULL DEFAULT false,
    `F0903` BOOLEAN NULL DEFAULT false,
    `F0904` BOOLEAN NULL DEFAULT false,
    `F0905` BOOLEAN NULL DEFAULT false,
    `F0906` BOOLEAN NULL DEFAULT false,
    `F0907` BOOLEAN NULL DEFAULT false,
    `F0908` BOOLEAN NULL DEFAULT false,
    `F0909` BOOLEAN NULL DEFAULT false,
    `F0910` BOOLEAN NULL DEFAULT false,
    `F0911` BOOLEAN NULL DEFAULT false,
    `F0912` BOOLEAN NULL DEFAULT false,
    `F0913` BOOLEAN NULL DEFAULT false,
    `F0914` BOOLEAN NULL DEFAULT false,
    `F0915` BOOLEAN NULL DEFAULT false,
    `F0916` BOOLEAN NULL DEFAULT false,
    `F0917` BOOLEAN NULL DEFAULT false,
    `F0918` BOOLEAN NULL DEFAULT false,
    `F0919` BOOLEAN NULL DEFAULT false,
    `F0920` BOOLEAN NULL DEFAULT false,
    `F1000` BOOLEAN NULL DEFAULT false,
    `F1001` BOOLEAN NULL DEFAULT false,
    `F1002` BOOLEAN NULL DEFAULT false,
    `F1003` BOOLEAN NULL DEFAULT false,
    `F1004` BOOLEAN NULL DEFAULT false,
    `F1005` BOOLEAN NULL DEFAULT false,
    `F1006` BOOLEAN NULL DEFAULT false,
    `F1007` BOOLEAN NULL DEFAULT false,
    `F1008` BOOLEAN NULL DEFAULT false,
    `F1009` BOOLEAN NULL DEFAULT false,
    `F1010` BOOLEAN NULL DEFAULT false,
    `F1011` BOOLEAN NULL DEFAULT false,
    `F1012` BOOLEAN NULL DEFAULT false,
    `F1013` BOOLEAN NULL DEFAULT false,
    `F1014` BOOLEAN NULL DEFAULT false,
    `F1015` BOOLEAN NULL DEFAULT false,
    `F1016` BOOLEAN NULL DEFAULT false,
    `F1017` BOOLEAN NULL DEFAULT false,
    `F1018` BOOLEAN NULL DEFAULT false,
    `F1019` BOOLEAN NULL DEFAULT false,
    `F1020` BOOLEAN NULL DEFAULT false,

    PRIMARY KEY (`User_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_ProcessGroupProcesses` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_ProcessGroupProcesses_AB_unique`(`A`, `B`),
    INDEX `_ProcessGroupProcesses_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_WorkGroupWorkers` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_WorkGroupWorkers_AB_unique`(`A`, `B`),
    INDEX `_WorkGroupWorkers_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `_WorkerWorkerGroups` (
    `A` VARCHAR(191) NOT NULL,
    `B` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `_WorkerWorkerGroups_AB_unique`(`A`, `B`),
    INDEX `_WorkerWorkerGroups_B_index`(`B`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TD_Order` ADD CONSTRAINT `TD_Order_Item1_CD_fkey` FOREIGN KEY (`Item1_CD`) REFERENCES `tm_item1`(`Item1_CD`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Order` ADD CONSTRAINT `TD_Order_Product_Grp_CD_fkey` FOREIGN KEY (`Product_Grp_CD`) REFERENCES `TM_WorkG`(`WorkG_CD`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Order` ADD CONSTRAINT `TD_Order_Customer_CD_fkey` FOREIGN KEY (`Customer_CD`) REFERENCES `TM_Customer`(`Customer_CD`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Procure` ADD CONSTRAINT `TD_Procure_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Plan` ADD CONSTRAINT `TD_Plan_Order_No_fkey` FOREIGN KEY (`Order_No`) REFERENCES `TD_Order`(`Order_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Plan` ADD CONSTRAINT `TD_Plan_Order_No_Parts_No_fkey` FOREIGN KEY (`Order_No`, `Parts_No`) REFERENCES `TD_Result`(`Order_No`, `Parts_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Cost` ADD CONSTRAINT `TD_Cost_Order_No_Parts_No_fkey` FOREIGN KEY (`Order_No`, `Parts_No`) REFERENCES `TD_Plan`(`Order_No`, `Parts_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_Schedule` ADD CONSTRAINT `TD_Schedule_Order_No_Parts_No_fkey` FOREIGN KEY (`Order_No`, `Parts_No`) REFERENCES `TD_Plan`(`Order_No`, `Parts_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TD_WIP` ADD CONSTRAINT `TD_WIP_Order_No_Parts_No_fkey` FOREIGN KEY (`Order_No`, `Parts_No`) REFERENCES `TD_Plan`(`Order_No`, `Parts_No`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TM_Process` ADD CONSTRAINT `TM_Process_Process_CD_fkey` FOREIGN KEY (`Process_CD`) REFERENCES `TM_Resource`(`Resource_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TM_Process` ADD CONSTRAINT `TM_Process_ProcessG_CD_fkey` FOREIGN KEY (`ProcessG_CD`) REFERENCES `TM_ProcessG`(`ProcessG_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TM_Process` ADD CONSTRAINT `TM_Process_ResourceG_CD_fkey` FOREIGN KEY (`ResourceG_CD`) REFERENCES `TM_ResourceG`(`ResourceG_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TM_Worker` ADD CONSTRAINT `TM_Worker_WorkG_CD_fkey` FOREIGN KEY (`WorkG_CD`) REFERENCES `TM_WorkG`(`WorkG_CD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_ProcessGroupProcesses` ADD CONSTRAINT `_ProcessGroupProcesses_A_fkey` FOREIGN KEY (`A`) REFERENCES `TM_Process`(`Process_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_ProcessGroupProcesses` ADD CONSTRAINT `_ProcessGroupProcesses_B_fkey` FOREIGN KEY (`B`) REFERENCES `TM_ProcessG`(`ProcessG_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkGroupWorkers` ADD CONSTRAINT `_WorkGroupWorkers_A_fkey` FOREIGN KEY (`A`) REFERENCES `TM_WorkG`(`WorkG_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkGroupWorkers` ADD CONSTRAINT `_WorkGroupWorkers_B_fkey` FOREIGN KEY (`B`) REFERENCES `TM_Worker`(`Worker_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkerWorkerGroups` ADD CONSTRAINT `_WorkerWorkerGroups_A_fkey` FOREIGN KEY (`A`) REFERENCES `TM_Worker`(`Worker_CD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `_WorkerWorkerGroups` ADD CONSTRAINT `_WorkerWorkerGroups_B_fkey` FOREIGN KEY (`B`) REFERENCES `TM_WorkerG`(`WorkerG_CD`) ON DELETE CASCADE ON UPDATE CASCADE;
